# Generated by Django 3.2.7 on 2021-09-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parlamentares',
            fields=[
                ('IdParlamentar', models.AutoField(primary_key=True, serialize=False)),
                ('NomeParlamentar', models.CharField(max_length=100)),
                ('EstadoParlamentar', models.CharField(max_length=100)),
                ('IdParlamentarEleito', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('IdPartido', models.AutoField(primary_key=True, serialize=False)),
                ('SiglaPartido', models.CharField(max_length=100)),
                ('NomePartido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Propostas',
            fields=[
                ('IdProposta', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoProposta', models.CharField(max_length=100)),
                ('DataProposta', models.DateField(default='2000-01-01')),
                ('Link1Proposta', models.CharField(max_length=100)),
                ('Link2Proposta', models.CharField(max_length=100)),
                ('Popularidade', models.IntegerField(default=0)),
                ('NomeProposta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.CharField(max_length=100)),
                ('Senha', models.CharField(max_length=100)),
                ('Nome', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VotacoesUsuarios',
            fields=[
                ('IdVotacao', models.AutoField(primary_key=True, serialize=False)),
                ('Voto', models.CharField(max_length=100)),
                ('IdProposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidaTinderApp.propostas')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidaTinderApp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='VotacoesParlamentares',
            fields=[
                ('IdVotacao', models.AutoField(primary_key=True, serialize=False)),
                ('Voto', models.CharField(max_length=100)),
                ('IdParlamentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidaTinderApp.parlamentares')),
                ('IdProposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidaTinderApp.propostas')),
            ],
        ),
        migrations.AddField(
            model_name='parlamentares',
            name='IdPartido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidaTinderApp.partidos'),
        ),
    ]
