# Generated by Django 3.2.7 on 2021-10-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidaTinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='IdParlamentar1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='IdParlamentar2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='IdParlamentar3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='IdPartido1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='IdPartido2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='IdPartido3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Idade',
            field=models.IntegerField(default=0),
        ),
    ]
