# Generated by Django 3.2.7 on 2021-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidaTinderApp', '0002_auto_20211005_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='PercentualParlamentar1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='PercentualParlamentar2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='PercentualParlamentar3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='PercentualPartido1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='PercentualPartido2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='PercentualPartido3',
            field=models.IntegerField(default=0),
        ),
    ]
