# Generated by Django 3.2.7 on 2021-10-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidaTinderApp', '0004_auto_20211005_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatousuario',
            name='QuantidadeParticipacoes',
            field=models.IntegerField(default=0),
        ),
    ]
